from pathlib import Path

DATA_DIR = Path("data") / "map_graph"
NODES_DIR = DATA_DIR / "nodes"
GRAPH_JSON = DATA_DIR / "map_graph.json"
COMPOSITE_IMAGE = DATA_DIR / "composite.png"

OVERLAP_RATIO_THRESHOLD = 0.4
OFFSET_CONFIDENCE_THRESHOLD = 0.4
MAX_NODE_COORD_DISPARITY_PX = 2.0
NEARBY_NODE_DISTANCE_RATIO = 0.3
NODE_UID_LENGTH = 12
